# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Русско-китайский параллельный корпус НКРЯ'
cntitle:          'CN Русско-китайский параллельный корпус НКРЯ'
tagline:          'НКРЯ'
description:      ''
cndescription:    ''
url:              http://localhost
baseurl:          ''
imageurl:         ''

author:
  name:           'Кирилл Семенов'
  url:            kir.semenow@yandex.ru

paginate:         5


# Custom vars
version:          Beta-0.0.1

github:
  repo:           https://github.com/ruzhcorp

#repository:       ruzhcorp/ruzhcorp.github.io