# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Русско-китайский параллельный корпус НКРЯ'
cntitle:          '俄语国家语料库·俄汉平行语料库'
entitle:          'Russian-Chinese parallel corpus of Russian National Corpus'
tagline:          'НКРЯ'
description:      ''
cndescription:    ''
endescription:    ''
url:              https://ruzhcorp.github.io
baseurl:          https://ruzhcorp.github.io/
imageurl:         http://ruzhcorp.github.io/

author:
  name:           'Кирилл Семенов'
  url:            kir.semenow@yandex.ru

paginate:         5

# Custom vars
version:          Beta-0.0.1

github:
  repo:           https://github.com/ruzhcorp
